"""create_market_data_tables

Revision ID: 246265422bb9
Revises: 71851897f519
Create Date: 2026-06-09 03:51:42.441510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246265422bb9'
down_revision: Union[str, Sequence[str], None] = '71851897f519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('size_range', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('ingestion_audit_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('job_count_attempted', sa.Integer(), nullable=False),
    sa.Column('job_count_inserted', sa.Integer(), nullable=False),
    sa.Column('job_count_duplicated', sa.Integer(), nullable=False),
    sa.Column('job_count_failed', sa.Integer(), nullable=False),
    sa.Column('log_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_sources',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_key', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_limit', sa.Integer(), nullable=True),
    sa.Column('rate_limit_remaining', sa.Integer(), nullable=True),
    sa.Column('rate_limit_reset_at', sa.DateTime(), nullable=True),
    sa.Column('error_count_24h', sa.Integer(), nullable=False),
    sa.Column('last_run_status', sa.String(length=50), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_sources_source_key'), 'job_sources', ['source_key'], unique=True)
    op.create_table('normalized_skills',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_skills_name'), 'normalized_skills', ['name'], unique=True)
    op.create_table('compensation_benchmarks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role_type', sa.String(length=100), nullable=False),
    sa.Column('location_normalized', sa.String(length=150), nullable=False),
    sa.Column('skill_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('p25_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('p50_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('p75_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['normalized_skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compensation_benchmarks_location_normalized'), 'compensation_benchmarks', ['location_normalized'], unique=False)
    op.create_index(op.f('ix_compensation_benchmarks_role_type'), 'compensation_benchmarks', ['role_type'], unique=False)
    op.create_index(op.f('ix_compensation_benchmarks_skill_id'), 'compensation_benchmarks', ['skill_id'], unique=False)
    op.create_table('job_ingestion_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('items_scraped', sa.Integer(), nullable=False),
    sa.Column('items_inserted', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_ingestion_runs_source_id'), 'job_ingestion_runs', ['source_id'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('raw_title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('compensation_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('compensation_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('post_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deduplicated_to_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('merged_into_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('dedupe_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deduplicated_to_id'], ['job_postings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merged_into_id'], ['job_postings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_company_id'), 'job_postings', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_postings_dedupe_fingerprint'), 'job_postings', ['dedupe_fingerprint'], unique=False)
    op.create_index(op.f('ix_job_postings_deduplicated_to_id'), 'job_postings', ['deduplicated_to_id'], unique=False)
    op.create_index(op.f('ix_job_postings_is_active'), 'job_postings', ['is_active'], unique=False)
    op.create_index(op.f('ix_job_postings_merged_into_id'), 'job_postings', ['merged_into_id'], unique=False)
    op.create_index(op.f('ix_job_postings_post_date'), 'job_postings', ['post_date'], unique=False)
    op.create_index(op.f('ix_job_postings_source_id'), 'job_postings', ['source_id'], unique=True)
    op.create_index(op.f('ix_job_postings_title'), 'job_postings', ['title'], unique=False)
    op.create_index(op.f('ix_job_postings_url'), 'job_postings', ['url'], unique=False)
    op.create_table('skill_relationships',
    sa.Column('parent_skill_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('child_skill_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['child_skill_id'], ['normalized_skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_skill_id'], ['normalized_skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_skill_id', 'child_skill_id')
    )
    op.create_table('skill_trends_daily',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('skill_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('posting_count', sa.Integer(), nullable=False),
    sa.Column('total_postings_count', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['normalized_skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_trends_daily_skill_id'), 'skill_trends_daily', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_trends_daily_snapshot_date'), 'skill_trends_daily', ['snapshot_date'], unique=False)
    op.create_table('compensation_records',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_posting_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('min_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_interval', sa.String(length=50), nullable=False),
    sa.Column('computed_annual_min', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('computed_annual_max', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('equity_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('equity_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location_normalized', sa.String(length=150), nullable=False),
    sa.Column('col_tier', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compensation_records_computed_annual_max'), 'compensation_records', ['computed_annual_max'], unique=False)
    op.create_index(op.f('ix_compensation_records_computed_annual_min'), 'compensation_records', ['computed_annual_min'], unique=False)
    op.create_index(op.f('ix_compensation_records_location_normalized'), 'compensation_records', ['location_normalized'], unique=False)
    op.create_table('dedupe_audit_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('primary_job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('merged_job_id', sa.String(length=36), nullable=False),
    sa.Column('merge_details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['primary_job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dedupe_audit_logs_primary_job_id'), 'dedupe_audit_logs', ['primary_job_id'], unique=False)
    op.create_table('job_duplicates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('primary_job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('duplicate_job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('title_similarity', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('company_similarity', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('description_similarity', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_duplicates_duplicate_job_id'), 'job_duplicates', ['duplicate_job_id'], unique=False)
    op.create_index(op.f('ix_job_duplicates_primary_job_id'), 'job_duplicates', ['primary_job_id'], unique=False)
    op.create_index(op.f('ix_job_duplicates_status'), 'job_duplicates', ['status'], unique=False)
    op.create_table('job_postings_skills',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_posting_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('skill_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('raw_mention', sa.String(length=100), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('context_sentence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['normalized_skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_skills_job_posting_id'), 'job_postings_skills', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_job_postings_skills_skill_id'), 'job_postings_skills', ['skill_id'], unique=False)
    op.create_table('raw_job_postings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_key', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_raw', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('salary_raw', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['job_ingestion_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_job_postings_company_name'), 'raw_job_postings', ['company_name'], unique=False)
    op.create_index(op.f('ix_raw_job_postings_external_id'), 'raw_job_postings', ['external_id'], unique=False)
    op.create_index(op.f('ix_raw_job_postings_ingestion_run_id'), 'raw_job_postings', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_raw_job_postings_source_key'), 'raw_job_postings', ['source_key'], unique=False)
    op.execute("""
CREATE MATERIALIZED VIEW mv_skill_trends AS
WITH current_30 AS (
    SELECT 
        skill_id,
        SUM(posting_count) as count_30d,
        AVG(frequency) as freq_30d
    FROM skill_trends_daily
    WHERE snapshot_date >= CURRENT_DATE - INTERVAL '30 days'
    GROUP BY skill_id
),
prior_30 AS (
    SELECT 
        skill_id,
        SUM(posting_count) as count_prev_30d,
        AVG(frequency) as freq_prev_30d
    FROM skill_trends_daily
    WHERE snapshot_date >= CURRENT_DATE - INTERVAL '60 days'
      AND snapshot_date < CURRENT_DATE - INTERVAL '30 days'
    GROUP BY skill_id
)
SELECT 
    ns.id as skill_id,
    ns.name as skill_name,
    COALESCE(c.count_30d, 0)::INTEGER as count_30d,
    COALESCE(c.freq_30d, 0.0)::NUMERIC(6,5) as freq_30d,
    COALESCE(p.count_prev_30d, 0)::INTEGER as count_prev_30d,
    COALESCE(p.freq_prev_30d, 0.0)::NUMERIC(6,5) as freq_prev_30d,
    CASE 
        WHEN COALESCE(p.freq_prev_30d, 0.0) = 0.0 THEN 0.0
        ELSE ((COALESCE(c.freq_30d, 0.0) - p.freq_prev_30d) / p.freq_prev_30d)::NUMERIC(6,3)
    END as velocity
FROM normalized_skills ns
LEFT JOIN current_30 c ON ns.id = c.skill_id
LEFT JOIN prior_30 p ON ns.id = p.skill_id;
""")
    op.execute("CREATE UNIQUE INDEX idx_mv_skill_trends_id ON mv_skill_trends(skill_id);")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP MATERIALIZED VIEW IF EXISTS mv_skill_trends CASCADE;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_job_postings_source_key'), table_name='raw_job_postings')
    op.drop_index(op.f('ix_raw_job_postings_ingestion_run_id'), table_name='raw_job_postings')
    op.drop_index(op.f('ix_raw_job_postings_external_id'), table_name='raw_job_postings')
    op.drop_index(op.f('ix_raw_job_postings_company_name'), table_name='raw_job_postings')
    op.drop_table('raw_job_postings')
    op.drop_index(op.f('ix_job_postings_skills_skill_id'), table_name='job_postings_skills')
    op.drop_index(op.f('ix_job_postings_skills_job_posting_id'), table_name='job_postings_skills')
    op.drop_table('job_postings_skills')
    op.drop_index(op.f('ix_job_duplicates_status'), table_name='job_duplicates')
    op.drop_index(op.f('ix_job_duplicates_primary_job_id'), table_name='job_duplicates')
    op.drop_index(op.f('ix_job_duplicates_duplicate_job_id'), table_name='job_duplicates')
    op.drop_table('job_duplicates')
    op.drop_index(op.f('ix_dedupe_audit_logs_primary_job_id'), table_name='dedupe_audit_logs')
    op.drop_table('dedupe_audit_logs')
    op.drop_index(op.f('ix_compensation_records_location_normalized'), table_name='compensation_records')
    op.drop_index(op.f('ix_compensation_records_computed_annual_min'), table_name='compensation_records')
    op.drop_index(op.f('ix_compensation_records_computed_annual_max'), table_name='compensation_records')
    op.drop_table('compensation_records')
    op.drop_index(op.f('ix_skill_trends_daily_snapshot_date'), table_name='skill_trends_daily')
    op.drop_index(op.f('ix_skill_trends_daily_skill_id'), table_name='skill_trends_daily')
    op.drop_table('skill_trends_daily')
    op.drop_table('skill_relationships')
    op.drop_index(op.f('ix_job_postings_url'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_title'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_source_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_post_date'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_merged_into_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_is_active'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_deduplicated_to_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_dedupe_fingerprint'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_company_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_job_ingestion_runs_source_id'), table_name='job_ingestion_runs')
    op.drop_table('job_ingestion_runs')
    op.drop_index(op.f('ix_compensation_benchmarks_skill_id'), table_name='compensation_benchmarks')
    op.drop_index(op.f('ix_compensation_benchmarks_role_type'), table_name='compensation_benchmarks')
    op.drop_index(op.f('ix_compensation_benchmarks_location_normalized'), table_name='compensation_benchmarks')
    op.drop_table('compensation_benchmarks')
    op.drop_index(op.f('ix_normalized_skills_name'), table_name='normalized_skills')
    op.drop_table('normalized_skills')
    op.drop_index(op.f('ix_job_sources_source_key'), table_name='job_sources')
    op.drop_table('job_sources')
    op.drop_table('ingestion_audit_logs')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
