"""create_wave_7_tables

Revision ID: 4990fdb25893
Revises: 45e117c1cbfb
Create Date: 2026-06-10 11:03:17.258798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4990fdb25893'
down_revision: Union[str, Sequence[str], None] = '45e117c1cbfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_schemas',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('platform_provider', sa.String(length=50), nullable=False),
    sa.Column('company_domain', sa.String(length=255), nullable=False),
    sa.Column('fields_schema', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_schemas_company_domain'), 'form_schemas', ['company_domain'], unique=True)
    op.create_table('workflow_execution_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('workflow_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('task_queue', sa.String(length=100), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_execution_logs_status'), 'workflow_execution_logs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_execution_logs_user_id'), 'workflow_execution_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_execution_logs_workflow_id'), 'workflow_execution_logs', ['workflow_id'], unique=True)
    op.create_table('application_outcomes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('application_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('predicted_fit_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_outcome', sa.String(length=50), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejection_stage', sa.String(length=50), nullable=True),
    sa.Column('prediction_error', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('days_to_response', sa.Integer(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=False),
    sa.Column('follow_up_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_outcomes_application_id'), 'application_outcomes', ['application_id'], unique=True)
    op.create_index(op.f('ix_application_outcomes_final_outcome'), 'application_outcomes', ['final_outcome'], unique=False)
    op.create_index(op.f('ix_application_outcomes_follow_up_date'), 'application_outcomes', ['follow_up_date'], unique=False)
    op.create_table('application_status_history',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('application_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_status_history_application_id'), 'application_status_history', ['application_id'], unique=False)
    op.create_table('application_workflow_checkpoints',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('application_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('current_state', sa.String(length=50), nullable=False),
    sa.Column('checkpoint_data', sa.JSON(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_workflow_checkpoints_application_id'), 'application_workflow_checkpoints', ['application_id'], unique=False)
    op.create_table('ats_audit_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('application_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ats_type', sa.String(length=50), nullable=False),
    sa.Column('request_url', sa.Text(), nullable=False),
    sa.Column('request_headers', sa.JSON(), nullable=False),
    sa.Column('request_body', sa.JSON(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ats_audit_logs_application_id'), 'ats_audit_logs', ['application_id'], unique=False)
    op.create_index(op.f('ix_ats_audit_logs_response_status'), 'ats_audit_logs', ['response_status'], unique=False)
    op.create_table('browser_execution_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('application_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_selector', sa.String(length=255), nullable=True),
    sa.Column('value_entered', sa.String(length=255), nullable=True),
    sa.Column('screenshot_path', sa.String(length=512), nullable=True),
    sa.Column('html_archive_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_execution_logs_application_id'), 'browser_execution_logs', ['application_id'], unique=False)
    op.create_table('form_execution_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('application_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('error_captured', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_execution_logs_application_id'), 'form_execution_logs', ['application_id'], unique=False)
    op.add_column('job_applications', sa.Column('opportunity_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('job_applications', sa.Column('resume_version_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('job_applications', sa.Column('cover_letter_text', sa.Text(), nullable=True))
    op.add_column('job_applications', sa.Column('custom_answers', sa.JSON(), nullable=True))
    op.add_column('job_applications', sa.Column('workflow_id', sa.String(length=255), nullable=True))
    op.add_column('job_applications', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_job_applications_opportunity_id'), 'job_applications', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_job_applications_resume_version_id'), 'job_applications', ['resume_version_id'], unique=False)
    op.create_index(op.f('ix_job_applications_workflow_id'), 'job_applications', ['workflow_id'], unique=False)
    op.create_foreign_key(None, 'job_applications', 'job_postings', ['opportunity_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'job_applications', 'profile_versions', ['resume_version_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('job_applications_opportunity_id_fkey', 'job_applications', type_='foreignkey')
    op.drop_constraint('job_applications_resume_version_id_fkey', 'job_applications', type_='foreignkey')
    op.drop_index(op.f('ix_job_applications_workflow_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_resume_version_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_opportunity_id'), table_name='job_applications')
    op.drop_column('job_applications', 'submitted_at')
    op.drop_column('job_applications', 'workflow_id')
    op.drop_column('job_applications', 'custom_answers')
    op.drop_column('job_applications', 'cover_letter_text')
    op.drop_column('job_applications', 'resume_version_id')
    op.drop_column('job_applications', 'opportunity_id')
    op.drop_index(op.f('ix_form_execution_logs_application_id'), table_name='form_execution_logs')
    op.drop_table('form_execution_logs')
    op.drop_index(op.f('ix_browser_execution_logs_application_id'), table_name='browser_execution_logs')
    op.drop_table('browser_execution_logs')
    op.drop_index(op.f('ix_ats_audit_logs_response_status'), table_name='ats_audit_logs')
    op.drop_index(op.f('ix_ats_audit_logs_application_id'), table_name='ats_audit_logs')
    op.drop_table('ats_audit_logs')
    op.drop_index(op.f('ix_application_workflow_checkpoints_application_id'), table_name='application_workflow_checkpoints')
    op.drop_table('application_workflow_checkpoints')
    op.drop_index(op.f('ix_application_status_history_application_id'), table_name='application_status_history')
    op.drop_table('application_status_history')
    op.drop_index(op.f('ix_application_outcomes_follow_up_date'), table_name='application_outcomes')
    op.drop_index(op.f('ix_application_outcomes_final_outcome'), table_name='application_outcomes')
    op.drop_index(op.f('ix_application_outcomes_application_id'), table_name='application_outcomes')
    op.drop_table('application_outcomes')
    op.drop_index(op.f('ix_workflow_execution_logs_workflow_id'), table_name='workflow_execution_logs')
    op.drop_index(op.f('ix_workflow_execution_logs_user_id'), table_name='workflow_execution_logs')
    op.drop_index(op.f('ix_workflow_execution_logs_status'), table_name='workflow_execution_logs')
    op.drop_table('workflow_execution_logs')
    op.drop_index(op.f('ix_form_schemas_company_domain'), table_name='form_schemas')
    op.drop_table('form_schemas')
    # ### end Alembic commands ###
