"""create_career_profile_tables

Revision ID: 71851897f519
Revises: 1575ab5b6621
Create Date: 2026-06-09 03:39:21.890384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71851897f519'
down_revision: Union[str, Sequence[str], None] = '1575ab5b6621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('current_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_profiles_user_id'), 'career_profiles', ['user_id'], unique=True)
    op.create_table('education',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_profile_id'), 'education', ['profile_id'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiences_company_name'), 'experiences', ['company_name'], unique=False)
    op.create_index(op.f('ix_experiences_profile_id'), 'experiences', ['profile_id'], unique=False)
    op.create_table('profile_versions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_versions_profile_id'), 'profile_versions', ['profile_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('role_description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_profile_id'), 'projects', ['profile_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('years_experience', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('proficiency', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_profile_id'), 'skills', ['profile_id'], unique=False)
    op.create_index(op.f('ix_skills_skill_name'), 'skills', ['skill_name'], unique=False)
    op.create_table('uploaded_resumes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_payload', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_resumes_profile_id'), 'uploaded_resumes', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_resumes_profile_id'), table_name='uploaded_resumes')
    op.drop_table('uploaded_resumes')
    op.drop_index(op.f('ix_skills_skill_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_profile_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_projects_profile_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_profile_versions_profile_id'), table_name='profile_versions')
    op.drop_table('profile_versions')
    op.drop_index(op.f('ix_experiences_profile_id'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_company_name'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_education_profile_id'), table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_career_profiles_user_id'), table_name='career_profiles')
    op.drop_table('career_profiles')
    # ### end Alembic commands ###
