"""create_wave_5_tables

Revision ID: 90c09ec38235
Revises: 246265422bb9
Create Date: 2026-06-09 11:52:02.458927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c09ec38235'
down_revision: Union[str, Sequence[str], None] = '246265422bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_role_specifications',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('typical_experience_years', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('typical_salary_p50', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('typical_salary_p75', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_role_specifications_role_title'), 'target_role_specifications', ['role_title'], unique=True)
    op.create_table('career_health_scores',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('skill_alignment_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('market_positioning_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('activity_health_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('compensation_alignment_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('profile_completeness_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('primary_insight', sa.Text(), nullable=False),
    sa.Column('top_driver', sa.String(length=255), nullable=False),
    sa.Column('top_detractor', sa.String(length=255), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_scores_user_computed', 'career_health_scores', ['user_id', 'computed_at'], unique=False)
    op.create_index(op.f('ix_career_health_scores_computed_at'), 'career_health_scores', ['computed_at'], unique=False)
    op.create_index(op.f('ix_career_health_scores_user_id'), 'career_health_scores', ['user_id'], unique=False)
    op.create_table('company_snapshots',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('active_postings_count', sa.Integer(), nullable=False),
    sa.Column('hiring_velocity', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('attractiveness_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_snapshots_company_id'), 'company_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_snapshots_snapshot_date'), 'company_snapshots', ['snapshot_date'], unique=False)
    op.create_table('company_watchlists',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'company_id')
    )
    op.create_table('dashboard_analytics_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('widget_name', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_analytics_events_created_at'), 'dashboard_analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_dashboard_analytics_events_user_id'), 'dashboard_analytics_events', ['user_id'], unique=False)
    op.create_table('position_deltas',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('top_3_prioritized_gaps', sa.JSON(), nullable=False),
    sa.Column('recommendation_summary', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_deltas_computed_at'), 'position_deltas', ['computed_at'], unique=False)
    op.create_index(op.f('ix_position_deltas_user_id'), 'position_deltas', ['user_id'], unique=True)
    op.create_table('ghost_posting_signals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_posting_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ghost_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_flagged_ghost', sa.Boolean(), nullable=False),
    sa.Column('age_days', sa.Integer(), nullable=False),
    sa.Column('repost_count', sa.Integer(), nullable=False),
    sa.Column('company_velocity_ratio', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('cohort_applications', sa.Integer(), nullable=False),
    sa.Column('cohort_interviews', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ghost_posting_signals_ghost_score'), 'ghost_posting_signals', ['ghost_score'], unique=False)
    op.create_index(op.f('ix_ghost_posting_signals_is_flagged_ghost'), 'ghost_posting_signals', ['is_flagged_ghost'], unique=False)
    op.create_index(op.f('ix_ghost_posting_signals_job_posting_id'), 'ghost_posting_signals', ['job_posting_id'], unique=True)
    op.create_table('opportunity_scores',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_posting_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('fit_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('skill_fit_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('experience_fit_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('compensation_fit_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('company_attractiveness_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('explanation_json', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_job_opp_scores', 'opportunity_scores', ['user_id', 'job_posting_id'], unique=True)
    op.create_index(op.f('ix_opportunity_scores_fit_score'), 'opportunity_scores', ['fit_score'], unique=False)
    op.create_index(op.f('ix_opportunity_scores_job_posting_id'), 'opportunity_scores', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_opportunity_scores_user_id'), 'opportunity_scores', ['user_id'], unique=False)
    op.add_column(
        'companies',
        sa.Column(
            'hiring_velocity_30d',
            sa.Numeric(precision=6, scale=2),
            server_default='0.00',
            nullable=False,
        ),
    )
    op.add_column(
        'companies',
        sa.Column(
            'hiring_velocity_90d',
            sa.Numeric(precision=6, scale=2),
            server_default='0.00',
            nullable=False,
        ),
    )
    op.add_column(
        'companies',
        sa.Column(
            'trend_direction',
            sa.String(length=50),
            nullable=True,
        ),
    )
    op.add_column(
        'companies',
        sa.Column(
            'attractiveness_score',
            sa.Numeric(precision=5, scale=2),
            server_default='0.00',
            nullable=False,
        ),
    )
    op.add_column(
        'companies',
        sa.Column(
            'last_aggregated_at',
            sa.DateTime(),
            nullable=True,
        ),
    )
    op.add_column(
        'job_postings',
        sa.Column(
            'is_ghost_posting',
            sa.Boolean(),
            server_default='false',
            nullable=False,
        ),
    )
    op.add_column(
        'job_postings',
        sa.Column(
            'ghost_score',
            sa.Numeric(precision=5, scale=2),
            server_default='0.00',
            nullable=False,
        ),
    )
    op.create_index(op.f('ix_job_postings_is_ghost_posting'), 'job_postings', ['is_ghost_posting'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_postings_is_ghost_posting'), table_name='job_postings')
    op.drop_column('job_postings', 'ghost_score')
    op.drop_column('job_postings', 'is_ghost_posting')
    op.drop_column('companies', 'last_aggregated_at')
    op.drop_column('companies', 'attractiveness_score')
    op.drop_column('companies', 'trend_direction')
    op.drop_column('companies', 'hiring_velocity_90d')
    op.drop_column('companies', 'hiring_velocity_30d')
    op.drop_index(op.f('ix_opportunity_scores_user_id'), table_name='opportunity_scores')
    op.drop_index(op.f('ix_opportunity_scores_job_posting_id'), table_name='opportunity_scores')
    op.drop_index(op.f('ix_opportunity_scores_fit_score'), table_name='opportunity_scores')
    op.drop_index('idx_user_job_opp_scores', table_name='opportunity_scores')
    op.drop_table('opportunity_scores')
    op.drop_index(op.f('ix_ghost_posting_signals_job_posting_id'), table_name='ghost_posting_signals')
    op.drop_index(op.f('ix_ghost_posting_signals_is_flagged_ghost'), table_name='ghost_posting_signals')
    op.drop_index(op.f('ix_ghost_posting_signals_ghost_score'), table_name='ghost_posting_signals')
    op.drop_table('ghost_posting_signals')
    op.drop_index(op.f('ix_position_deltas_user_id'), table_name='position_deltas')
    op.drop_index(op.f('ix_position_deltas_computed_at'), table_name='position_deltas')
    op.drop_table('position_deltas')
    op.drop_index(op.f('ix_dashboard_analytics_events_user_id'), table_name='dashboard_analytics_events')
    op.drop_index(op.f('ix_dashboard_analytics_events_created_at'), table_name='dashboard_analytics_events')
    op.drop_table('dashboard_analytics_events')
    op.drop_table('company_watchlists')
    op.drop_index(op.f('ix_company_snapshots_snapshot_date'), table_name='company_snapshots')
    op.drop_index(op.f('ix_company_snapshots_company_id'), table_name='company_snapshots')
    op.drop_table('company_snapshots')
    op.drop_index(op.f('ix_career_health_scores_user_id'), table_name='career_health_scores')
    op.drop_index(op.f('ix_career_health_scores_computed_at'), table_name='career_health_scores')
    op.drop_index('idx_health_scores_user_computed', table_name='career_health_scores')
    op.drop_table('career_health_scores')
    op.drop_index(op.f('ix_target_role_specifications_role_title'), table_name='target_role_specifications')
    op.drop_table('target_role_specifications')
    # ### end Alembic commands ###
