"""create_wave_8_tables

Revision ID: bb2b3a05cd78
Revises: 4990fdb25893
Create Date: 2026-06-10 20:28:57.737691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb2b3a05cd78'
down_revision: Union[str, Sequence[str], None] = '4990fdb25893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_models',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=100), nullable=False),
    sa.Column('mlflow_model_version', sa.String(length=50), nullable=False),
    sa.Column('brier_score', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('roc_auc', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mlflow_run_id')
    )
    op.create_index('idx_calibration_models_active', 'calibration_models', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_table('eval_datasets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('expected_output', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_datasets_component_name'), 'eval_datasets', ['component_name'], unique=False)
    op.create_table('eval_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('commit_sha', sa.String(length=100), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('average_latency_ms', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('overall_accuracy', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_status'), 'eval_runs', ['status'], unique=False)
    op.create_table('ml_model_registry',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=100), nullable=False),
    sa.Column('version_tag', sa.String(length=50), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('accuracy_metrics', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'version_tag', name='uq_name_version')
    )
    op.create_index('idx_model_registry_stage', 'ml_model_registry', ['model_name', 'current_stage'], unique=False)
    op.create_table('peer_cohorts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('cohort_name', sa.String(length=150), nullable=False),
    sa.Column('cluster_centroid', sa.JSON(), nullable=False),
    sa.Column('metrics_cache', sa.JSON(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort_name')
    )
    op.create_table('cohort_memberships',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('peer_cohort_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('salary_percentile', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('skills_percentile', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('outcome_velocity_percentile', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['peer_cohort_id'], ['peer_cohorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_cohort_memberships_cohort', 'cohort_memberships', ['peer_cohort_id'], unique=False)
    op.create_table('eval_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('eval_run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dataset_item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('actual_output', sa.JSON(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_passed', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_item_id'], ['eval_datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_results_eval_run_id'), 'eval_results', ['eval_run_id'], unique=False)
    op.create_table('calibrated_predictions_log',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('calibration_model_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('raw_fit_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('calibrated_probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('actual_outcome', sa.String(length=50), nullable=True),
    sa.Column('realized_target', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calibration_model_id'], ['calibration_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calibrated_predictions_user', 'calibrated_predictions_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('idx_calibrated_predictions_user', table_name='calibrated_predictions_log')
    op.drop_table('calibrated_predictions_log')
    op.drop_index(op.f('ix_eval_results_eval_run_id'), table_name='eval_results')
    op.drop_table('eval_results')
    op.drop_index('idx_cohort_memberships_cohort', table_name='cohort_memberships')
    op.drop_table('cohort_memberships')
    op.drop_table('peer_cohorts')
    op.drop_index('idx_model_registry_stage', table_name='ml_model_registry')
    op.drop_table('ml_model_registry')
    op.drop_index(op.f('ix_eval_runs_status'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_eval_datasets_component_name'), table_name='eval_datasets')
    op.drop_table('eval_datasets')
    op.drop_index('idx_calibration_models_active', table_name='calibration_models', postgresql_where=sa.text('is_active = true'))
    op.drop_table('calibration_models')
    # ### end Alembic commands ###
